// Code generated by internal/gen. DO NOT EDIT.

//go:build rangefunc

package xiter

func MapKeys() {}

func Limit() {}

func IsSorted() {}

func Windows() {}

func Merge() {}

func CollectSplit() {}

func OfValue() {}

func Max() {}

func Skip() {}

func AppendSplitTo() {}

func Handle() {}

func Concat() {}

func StringSplit() {}

func Fold() {}

func CollectSize() {}

func Product() {}

func RecvContext() {}

func OfMap() {}

func Or() {}

func Reduce() {}

func Runes() {}

func PartitionInto() {}

func Bytes() {}

func Sum() {}

func Min() {}

func AppendTo() {}

func Collect() {}

func OfSliceIndex() {}

func Any() {}

func All() {}

func IsSortedFunc() {}

func V2() {}

func Equal() {}

func ToPair() {}

func Flatten() {}

func V1() {}

func Partition() {}

func Find() {}

func OfSlice() {}

func Map() {}

func Generate() {}

func EqualFunc() {}

func Of() {}

func Zip() {}

func GoPull() {}

func MergeFunc() {}

func Split() {}

func Drain() {}

func OfChan() {}

func Split2() {}

func MapValues() {}

func FromPair() {}

func Contains() {}

func Chunks() {}

func Enumerate() {}

func Filter() {}

func SendContext() {}

func Cache() {}
