name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  go-vet:
    name: go vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: go vet
        run: go vet -v ./...

  go-test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: go test
        run: go test -v ./...
